### Data Filtering
What this notebook does
- import country wide admin (county, constituencies and wards) and osm road data
- filter data to migori county
- export the data as gpkg for pushing to remote repo

In [1]:
# add libraries
from pathlib import Path
import geopandas as gpd
import pandas as pd

In [9]:
# config working directory
data_dir = Path.cwd().parent/'raw_datasets'
data_dir
output_dir = Path.cwd().parent/'processed_datasets'
output_dir.mkdir(exist_ok=True, parents=True)

In [10]:
# import admin data
adm1 = gpd.read_file(data_dir/'ken_admin_boundaries/ken_admin1.shp')
adm2 = gpd.read_file(data_dir/'ken_admin_boundaries/ken_admin2.shp')
adm4 = gpd.read_file(data_dir/'Kenya_Wards/kenya_wards.shp')
adm4.head(2)

,gid,pop2009,county,subcounty,ward,uid,scuid,cuid,geometry
0,241,17431.0,ISIOLO,Isiolo Sub County,WABERA,rIdiIpv9fBt,I2LYLqKU6AW,bzOfj0iwfDH,"POLYGON ((37.59968 0.40029, 37.59976 0.40004, ..."
1,1455,18755.0,Migori,Rongo Sub County,North Kamagambo Ward,QC41mItjIzF,fT37q3rXQ35,fVra3Pwta0Q,"POLYGON ((34.59938 -0.65054, 34.60006 -0.65069..."

In [11]:
# select migori dataset
Migori = adm1[adm1['adm1_name'] == 'Migori']
constituencies = adm2[adm2['adm1_name'] == 'Migori'] 
wards = adm4[adm4['county']== 'Migori']
wards

,gid,pop2009,county,subcounty,ward,uid,scuid,cuid,geometry
1,1455,18755.0,Migori,Rongo Sub County,North Kamagambo Ward,QC41mItjIzF,fT37q3rXQ35,fVra3Pwta0Q,"POLYGON ((34.59938 -0.65054, 34.60006 -0.65069..."
2,1456,27756.0,Migori,Rongo Sub County,Central Kamagambo Ward,M8rGveWTIMm,fT37q3rXQ35,fVra3Pwta0Q,"POLYGON ((34.61175 -0.73357, 34.61183 -0.73357..."
3,1457,27179.0,Migori,Rongo Sub County,South Kamagambo Ward,DABObbHgPMX,fT37q3rXQ35,fVra3Pwta0Q,"POLYGON ((34.61751 -0.87293, 34.6175 -0.87294,..."
4,1458,22874.0,Migori,Awendo Sub County,North Sakwa Ward,EmSsP2C6A3h,ka9Uv3Ckcbd,fVra3Pwta0Q,"POLYGON ((34.55349 -0.75193, 34.55364 -0.75195..."
5,1459,36200.0,Migori,Awendo Sub County,South Sakwa Ward,OpbsijPbYuv,ka9Uv3Ckcbd,fVra3Pwta0Q,"POLYGON ((34.57991 -0.84281, 34.57996 -0.84282..."
6,1460,22278.0,Migori,Awendo Sub County,West Sakwa Ward,nLwQA56EFmD,ka9Uv3Ckcbd,fVra3Pwta0Q,"POLYGON ((34.5287 -0.78517, 34.52867 -0.78522,..."
7,1461,27561.0,Migori,Awendo Sub County,Central Sakwa Ward,jmeydKjWYw7,ka9Uv3Ckcbd,fVra3Pwta0Q,"POLYGON ((34.5488 -0.79767, 34.54887 -0.79767,..."
8,1462,18567.0,Migori,Suna East Sub County,God Jope Ward,Fp2Wuqu3GAI,nHEr5EciFh0,fVra3Pwta0Q,"POLYGON ((34.53646 -1.0435, 34.53681 -1.04383,..."
9,1463,27645.0,Migori,Suna East Sub County,Suna Central Ward,QAxizS8H0d7,nHEr5EciFh0,fVra3Pwta0Q,"POLYGON ((34.47737 -1.04108, 34.47749 -1.04124..."
10,1464,33642.0,Migori,Suna East Sub County,Kakrao Ward,SUvzbKCIzyN,nHEr5EciFh0,fVra3Pwta0Q,"POLYGON ((34.36522 -0.98149, 34.36653 -0.98228..."
11,1465,17267.0,Migori,Suna East Sub County,Kwa Ward,YKABD0bh2a7,nHEr5EciFh0,fVra3Pwta0Q,"POLYGON ((34.61283 -1.07048, 34.61419 -1.0719,..."
12,1466,24096.0,Migori,Suna West Sub County,Wiga Ward,kxIw7ZzqXPq,VtuwXD7O1O9,fVra3Pwta0Q,"POLYGON ((34.33234 -0.99949, 34.33351 -0.99956..."
13,1467,17952.0,Migori,Suna West Sub County,Waseweta Ii Ward,KwrilS23iAS,VtuwXD7O1O9,fVra3Pwta0Q,"POLYGON ((34.38046 -1.05148, 34.3805 -1.05148,..."
14,1468,32847.0,Migori,Suna West Sub County,Ragana-oruba Ward,PPEvdyHP6uZ,VtuwXD7O1O9,fVra3Pwta0Q,"POLYGON ((34.44911 -1.0542, 34.44933 -1.05421,..."
15,1469,19232.0,Migori,Suna West Sub County,Wasimbete Ward,c2OOtR8JNjy,VtuwXD7O1O9,fVra3Pwta0Q,"POLYGON ((34.27417 -1.07691, 34.27422 -1.07692..."
16,1470,26786.0,Migori,Uriri Sub County,West Kanyamkago Ward,ziaLqezx6rb,fCInDXluNhx,fVra3Pwta0Q,"POLYGON ((34.3734 -0.91424, 34.37348 -0.91425,..."
17,1471,30396.0,Migori,Uriri Sub County,North Kanyamkago Ward,LXYI6dwqHoR,fCInDXluNhx,fVra3Pwta0Q,"POLYGON ((34.39091 -0.81683, 34.39225 -0.81764..."
18,1472,17814.0,Migori,Uriri Sub County,Central Kanyamkago Ward,P9SReXKzjbO,fCInDXluNhx,fVra3Pwta0Q,"POLYGON ((34.40661 -0.89841, 34.40884 -0.89871..."
19,1473,27719.0,Migori,Uriri Sub County,South Kanyamkago Ward,FdBel1HNlGu,fCInDXluNhx,fVra3Pwta0Q,"POLYGON ((34.50422 -0.91559, 34.50522 -0.91564..."
20,1474,13036.0,Migori,Uriri Sub County,East Kanyamkago Ward,IgyJtGgB69M,fCInDXluNhx,fVra3Pwta0Q,"POLYGON ((34.55815 -0.98621, 34.5582 -0.98633,..."
21,1475,21775.0,Migori,Nyatike Sub County,Kachieng' Ward,yowhezRzMGg,D2lsuEzZAJP,fVra3Pwta0Q,"POLYGON ((34.16753 -0.77385, 34.16793 -0.77408..."
22,1486,22683.0,Migori,Kuria West Sub County,Masaba Ward,zTD1Z6ldaEx,jtBjNpL9FXS,fVra3Pwta0Q,"POLYGON ((34.6047 -1.1047, 34.60473 -1.10477, ..."
23,1490,20439.0,Migori,Kuria East Sub County,Ntimaru West Ward,dkHXkFhXXxJ,THm2tCJa2ZQ,fVra3Pwta0Q,"POLYGON ((34.68379 -1.33242, 34.68388 -1.33277..."
135,1476,14331.0,Migori,Nyatike Sub County,Kanyasa Ward,ONNWmIVc48N,D2lsuEzZAJP,fVra3Pwta0Q,"POLYGON ((34.21272 -0.76594, 34.21292 -0.76607..."
136,1477,30697.0,Migori,Nyatike Sub County,North Kadem Ward,ry7pGVSoLwL,D2lsuEzZAJP,fVra3Pwta0Q,"POLYGON ((34.3005 -0.8414, 34.30051 -0.8414, 3..."
137,1478,22691.0,Migori,Nyatike Sub County,Macalder/kanyarwanda Ward,NGRN2o3qN2r,D2lsuEzZAJP,fVra3Pwta0Q,"POLYGON ((34.33925 -0.91948, 34.33927 -0.91986..."
138,1479,9775.0,Migori,Nyatike Sub County,Kaler Ward,edSLoK3sx6W,D2lsuEzZAJP,fVra3Pwta0Q,"POLYGON ((34.27772 -1.06197, 34.27733 -1.0631,..."
139,1480,22338.0,Migori,Nyatike Sub County,Got Kachola Ward,wQeQqCSAjRy,D2lsuEzZAJP,fVra3Pwta0Q,"POLYGON ((34.14429 -0.92437, 34.14456 -0.92456..."
140,1481,23018.0,Migori,Nyatike Sub County,Muhuru Ward,nQxxjPy6J5A,D2lsuEzZAJP,fVra3Pwta0Q,"MULTIPOLYGON (((34.05673 -1.03193, 34.05669 -1..."
141,1482,19476.0,Migori,Kuria West Sub County,Bukira East Ward,lOqK0cwQKaH,jtBjNpL9FXS,fVra3Pwta0Q,"POLYGON ((34.61239 -1.14949, 34.61247 -1.15009..."
142,1483,18140.0,Migori,Kuria West Sub County,Bukira Central/ikerege Ward,mLrXAhflEvn,jtBjNpL9FXS,fVra3Pwta0Q,"POLYGON ((34.59765 -1.19332, 34.5978 -1.19354,..."
143,1484,23556.0,Migori,Kuria West Sub County,Isibania Ward,ItjmRWn5IsE,jtBjNpL9FXS,fVra3Pwta0Q,"POLYGON ((34.48093 -1.22845, 34.48138 -1.22891..."
161,1485,20982.0,Migori,Kuria West Sub County,Mokerero Ward,CpQX2anrUJk,jtBjNpL9FXS,fVra3Pwta0Q,"POLYGON ((34.52018 -1.20124, 34.52011 -1.20171..."
163,1487,22562.0,Migori,Kuria West Sub County,Tagare Ward,EFFhTqzNEYT,jtBjNpL9FXS,fVra3Pwta0Q,"POLYGON ((34.45545 -1.12561, 34.45768 -1.12594..."
166,1488,26542.0,Migori,Kuria West Sub County,Nyamosense/komosoko Ward,DfL4XXliaq1,jtBjNpL9FXS,fVra3Pwta0Q,"POLYGON ((34.42926 -1.12283, 34.42938 -1.12331..."
167,1489,20312.0,Migori,Kuria East Sub County,Gokeharaka/getambwega Ward,Y9n3cjtnU4R,THm2tCJa2ZQ,fVra3Pwta0Q,"POLYGON ((34.54216 -1.22091, 34.54895 -1.22295..."
168,1491,11730.0,Migori,Kuria East Sub County,Ntimaru East Ward,C6U23QgqMCn,THm2tCJa2ZQ,fVra3Pwta0Q,"POLYGON ((34.70791 -1.2973, 34.70791 -1.29731,..."
169,1492,22293.0,Migori,Kuria East Sub County,Nyabasi East Ward,xUtluqIJmBZ,THm2tCJa2ZQ,fVra3Pwta0Q,"POLYGON ((34.67057 -1.19975, 34.67092 -1.19976..."
170,1493,27371.0,Migori,Kuria East Sub County,Nyabasi West Ward,k00olmG2C2e,THm2tCJa2ZQ,fVra3Pwta0Q,"POLYGON ((34.64408 -1.16901, 34.64409 -1.16904..."
171,1494,26857.0,Migori,Rongo Sub County,East Kamagambo Ward,l8btuTBphnw,fT37q3rXQ35,fVra3Pwta0Q,"MULTIPOLYGON (((34.55633 -0.67035, 34.55637 -0..."

In [14]:
# export to gpkg
Migori.to_file(output_dir/'Migori.gpkg', driver='GPKG')
constituencies.to_file(output_dir/'Migori_const.gpkg', driver='GPKG')
wards.to_file(output_dir/'Migori_wards.gpkg', driver='GPKG')

In [15]:
# import road data
roads = gpd.read_file(data_dir/'hotosm_ken_roads_osm/roads_lines.shp')
roads.head(2)

,id,name,name_en,name_sw,highway,surface,smoothness,width,lanes,oneway,...,adm1_pcode,adm1_name,adm2_pcode,adm2_name,adm3_pcode,adm3_name,adm4_pcode,adm4_name,name_latin,geometry
0,way/164794867,NaN,NaN,NaN,path,NaN,NaN,NaN,NaN,NaN,...,KE007,Garissa,KE007030,Dadaab,None,None,None,None,NaN,"LINESTRING (40.37972 0.00704, 40.38 0.00709, 4..."
1,way/164841194,NaN,NaN,NaN,path,NaN,NaN,NaN,NaN,NaN,...,KE007,Garissa,KE007030,Dadaab,None,None,None,None,NaN,"LINESTRING (40.38125 0.00667, 40.38127 0.00675..."

In [16]:
# filter to migori and export to gpkg
migori_roads = roads[roads['adm1_name'] == 'Migori']
migori_roads.to_file(output_dir/'roads.gpkg', driver='GPKG')

In [20]:
# wash data
wash = pd.read_csv(data_dir/'kenyaWASH.csv')
wash.head(2)

,row_id,source,lat_deg,lon_deg,report_date,status_id,water_source_clean,water_source_category,water_tech_clean,_water_tech_category,...,subjective_quality,new_georeferenced_column_,lat_lon_deg,public_data_source,converted,count,created_timestamp,updated,is_duplicate,dataset_title
0,778031,Evidence Action,-1.037077,34.358046,2014-03-14T00:00:00.000,Yes,Borehole/Tubewell,Well,NaN,NaN,...,NaN,POINT (34.3580455285 -1.0370774269),"(-1.0370774269°, 34.3580455285°)",https://catalog.waterpointdata.org/datafiles/e...,NaN,1,2020-09-30T17:46:39.000,2020-09-30T17:46:39.000,NaN,Evidence Action_Kenya_2012-2016
1,652654,Evidence Action,-0.821468,34.268340,2023-12-15T00:00:00.000,Yes,Borehole/Tubewell,Well,NaN,NaN,...,NaN,POINT (34.26834 -0.8214683333),"(-0.8214683333°, 34.26834°)",https://catalog.waterpointdata.org/datafiles/e...,NaN,1,2024-04-18T19:20:18.000,2024-04-18T19:20:18.000,NaN,Evidence Action_Kenya_2023-2024

In [21]:
wash.columns

Index(['row_id', 'source', 'lat_deg', 'lon_deg', 'report_date', 'status_id',
       'water_source_clean', 'water_source_category', 'water_tech_clean',
       '_water_tech_category', 'facility_type', 'clean_country_name',
       'clean_country_id', 'clean_adm1', 'clean_adm2', 'clean_adm3',
       'clean_adm4', 'install_year', 'installer', 'rehab_year',
       'rehabilitator', 'management_clean', 'status_clean', 'pay_clean',
       'fecal_coliform_presence', 'fecal_coliform_value',
       'subjective_quality_clean', 'activity_id', 'scheme_id', 'wpdx_id',
       'notes', 'orig_lnk', 'photo_lnk', 'country_id', 'data_lnk',
       'distance_to_primary', 'distance_to_secondary', 'distance_to_tertiary',
       'distance_to_city', 'distance_to_town', 'water_point_history',
       'local_population', 'served_population', 'rehab_priority',
       '_pop_who_would_gain_access', 'crucialness', 'pressure', 'usage_cap',
       'days_since_report', 'staleness_score', 'is_latest', 'location_id',
       'is_urban', 'cluster_size', 'country_name', 'water_source',
       'water_tech', 'status', 'adm1', 'adm2', 'adm3', 'management', 'pay',
       'subjective_quality', 'new_georeferenced_column_', 'lat_lon_deg',
       'public_data_source', 'converted', 'count', 'created_timestamp',
       'updated', 'is_duplicate', 'dataset_title'],
      dtype='str')

In [22]:
# filter to migori and export
wash_migori = wash[wash['clean_adm1'] == 'Migori']
wash_migori.to_csv(output_dir/'wash.csv', index=False)

,row_id,source,lat_deg,lon_deg,report_date,status_id,water_source_clean,water_source_category,water_tech_clean,_water_tech_category,...,subjective_quality,new_georeferenced_column_,lat_lon_deg,public_data_source,converted,count,created_timestamp,updated,is_duplicate,dataset_title
0,778031,Evidence Action,-1.037077,34.358046,2014-03-14T00:00:00.000,Yes,Borehole/Tubewell,Well,NaN,NaN,...,NaN,POINT (34.3580455285 -1.0370774269),"(-1.0370774269°, 34.3580455285°)",https://catalog.waterpointdata.org/datafiles/e...,NaN,1,2020-09-30T17:46:39.000,2020-09-30T17:46:39.000,NaN,Evidence Action_Kenya_2012-2016
1,652654,Evidence Action,-0.821468,34.268340,2023-12-15T00:00:00.000,Yes,Borehole/Tubewell,Well,NaN,NaN,...,NaN,POINT (34.26834 -0.8214683333),"(-0.8214683333°, 34.26834°)",https://catalog.waterpointdata.org/datafiles/e...,NaN,1,2024-04-18T19:20:18.000,2024-04-18T19:20:18.000,NaN,Evidence Action_Kenya_2023-2024